/*
 * generated by Xtext
 */
package jp.pizzafactory.dsl.rin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ItronCfgUiModule extends jp.pizzafactory.dsl.rin.ui.AbstractItronCfgUiModule {
	public ItronCfgUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
