/*
 * generated by Xtext
 */
package jp.pizzafactory.dsl.rin.ui.contentassist

import jp.pizzafactory.dsl.rin.ui.contentassist.AbstractItronCfgProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ItronCfgProposalProvider extends AbstractItronCfgProposalProvider {
}
