/*
 * generated by Xtext
 */
package jp.pizzafactory.dsl.rin.ui.outline

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class ItronCfgOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
	
	def text(Integer i) {
		i.toString
	}
}
