/*
 * generated by Xtext
 */
package jp.pizzafactory.dsl.rin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ItronCfgRuntimeModule extends jp.pizzafactory.dsl.rin.AbstractItronCfgRuntimeModule {

}
