/*
 * generated by Xtext
 */
package jp.pizzafactory.dsl.rin;

import jp.pizzafactory.dsl.rin.ItronCfgStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ItronCfgStandaloneSetup extends ItronCfgStandaloneSetupGenerated{

	public static void doSetup() {
		new ItronCfgStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

